In [456]:
#-cleans and prepares raw, messy data so that machine learning models can understand it and make accurate predictions

In [457]:
#1. Import Libraries
#2. Load Dataset
#3. Check Missing Values Again
#4. Handle Missing Values
#5. Verify Missing Values
#6. Handle Duplicates
#7. Handle Outliers
#8. Save Cleaned Dataset

In [458]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

In [459]:
df = pd.read_csv("../data/AmesHousing.csv")

In [460]:
print(df.shape)

(2930, 82)

In [461]:
# we check again because it should be independent like if someone opens this preprocessing it should run independent without the dependent of eda.py file. notebooks should be independent

In [462]:
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [463]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_summary = missing_summary[
    missing_summary["Missing Count"] > 0
].sort_values(
    by="Missing Count",
    ascending=False
)

missing_summary

                Missing Count  Missing Percentage
Pool QC                  2917           99.556314
Misc Feature             2824           96.382253
Alley                    2732           93.242321
Fence                    2358           80.477816
Mas Vnr Type             1775           60.580205
Fireplace Qu             1422           48.532423
Lot Frontage              490           16.723549
Garage Cond               159            5.426621
Garage Qual               159            5.426621
Garage Finish             159            5.426621
Garage Yr Blt             159            5.426621
Garage Type               157            5.358362
Bsmt Exposure              83            2.832765
BsmtFin Type 2             81            2.764505
Bsmt Cond                  80            2.730375
Bsmt Qual                  80            2.730375
BsmtFin Type 1             80            2.730375
Mas Vnr Area               23            0.784983
Bsmt Half Bath              2            0.068259
Bsmt Full Bath              2            0.068259
BsmtFin SF 1                1            0.034130
Garage Cars                 1            0.034130
Garage Area                 1            0.034130
Total Bsmt SF               1            0.034130
Bsmt Unf SF                 1            0.034130
BsmtFin SF 2                1            0.034130
Electrical                  1            0.034130

In [464]:
# since we know there were more missing values in pool quality wwe need to know the info of it
df["Pool QC"].value_counts(dropna=False)
#The hidden rows are revealed if we use dropna

Pool QC
NaN    2917
Ex        4
Gd        4
TA        3
Fa        2
Name: count, dtype: int64

In [465]:
none_columns = [
    "Pool QC",
    "Alley",
    "Fence",
    "Misc Feature"
]

for column in none_columns:
    df[column] = df[column].fillna("None")

    #if we use any other colums it would may lead to some misconception of data like it have pools but quality is not mentioned

In [466]:
df[none_columns].isnull().sum()
#just checking it

Pool QC         0
Alley           0
Fence           0
Misc Feature    0
dtype: int64

In [467]:
remaining_missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing percentage": (df.isnull().sum() / len(df)) * 100
})
remaining_missing = remaining_missing[
    remaining_missing["Missing Count"]>0
].sort_values(by="Missing Count",ascending=False)
remaining_missing

                Missing Count  Missing percentage
Mas Vnr Type             1775           60.580205
Fireplace Qu             1422           48.532423
Lot Frontage              490           16.723549
Garage Qual               159            5.426621
Garage Finish             159            5.426621
Garage Yr Blt             159            5.426621
Garage Cond               159            5.426621
Garage Type               157            5.358362
Bsmt Exposure              83            2.832765
BsmtFin Type 2             81            2.764505
BsmtFin Type 1             80            2.730375
Bsmt Cond                  80            2.730375
Bsmt Qual                  80            2.730375
Mas Vnr Area               23            0.784983
Bsmt Full Bath              2            0.068259
Bsmt Half Bath              2            0.068259
BsmtFin SF 1                1            0.034130
BsmtFin SF 2                1            0.034130
Bsmt Unf SF                 1            0.034130
Electrical                  1            0.034130
Garage Cars                 1            0.034130
Garage Area                 1            0.034130
Total Bsmt SF               1            0.034130

In [468]:
df["Fireplace Qu"].value_counts(dropna=False)

Fireplace Qu
NaN    1422
Gd      744
TA      600
Fa       75
Po       46
Ex       43
Name: count, dtype: int64

In [469]:
df["Fireplace Qu"] = df["Fireplace Qu"].fillna("None")

In [470]:
df["Fireplace Qu"].isnull().sum()

np.int64(0)

In [471]:
#mode() - to handle missing categorical data by replacing blank spots with the most frequently occurring value.

In [472]:
df["Fireplace Qu"].value_counts(dropna=False)

Fireplace Qu
None    1422
Gd       744
TA       600
Fa        75
Po        46
Ex        43
Name: count, dtype: int64

In [473]:
df["Fireplace Qu"]=df["Fireplace Qu"].fillna("None")

In [474]:
df["Fireplace Qu"].isnull().sum()

np.int64(0)

In [475]:
df["Garage Type"].value_counts(dropna=False)

Garage Type
Attchd     1731
Detchd      782
BuiltIn     186
NaN         157
Basment      36
2Types       23
CarPort      15
Name: count, dtype: int64

In [476]:
garage_cat=["Garage Type",
    "Garage Finish",
    "Garage Qual",
    "Garage Cond"
            ]
for column in garage_cat:
    df[column]= df[column].fillna("None")

In [477]:
garage_num=[
    "Garage Yr Blt",
    "Garage Cars",
    "Garage Area"
]
for column in garage_num:
    df[column]=df[column].fillna(0)

In [478]:
#verify both is that every column have none filled completely
df[garage_cat + garage_num].isnull().sum()

#Because the missing values don't indicate missing information. They indicate that the house has no garage. A garage area of 0 correctly represents the absence of a garage, whereas using the median would incorrectly assign a garage size to houses that don't have one.

Garage Type      0
Garage Finish    0
Garage Qual      0
Garage Cond      0
Garage Yr Blt    0
Garage Cars      0
Garage Area      0
dtype: int64

In [479]:
df["Bsmt Qual"].value_counts(dropna=False)

Bsmt Qual
TA     1283
Gd     1219
Ex      258
Fa       88
NaN      80
Po        2
Name: count, dtype: int64

In [480]:
basement_num = [
    "Bsmt Full Bath",
    "Bsmt Half Bath",
    "BsmtFin SF 1",
    "BsmtFin SF 2",
    "Bsmt Unf SF",
    "Total Bsmt SF"
]

for column in basement_num:
    df[column] = df[column].fillna(0)

In [481]:
basement_cat = [
    "Bsmt Qual",
    "Bsmt Cond",
    "Bsmt Exposure",
    "BsmtFin Type 1",
    "BsmtFin Type 2"
]

for column in basement_cat:
    df[column] = df[column].fillna("None")

In [482]:
df[basement_cat + basement_num].isnull().sum()

Bsmt Qual         0
Bsmt Cond         0
Bsmt Exposure     0
BsmtFin Type 1    0
BsmtFin Type 2    0
Bsmt Full Bath    0
Bsmt Half Bath    0
BsmtFin SF 1      0
BsmtFin SF 2      0
Bsmt Unf SF       0
Total Bsmt SF     0
dtype: int64

In [483]:
df["Lot Frontage"].isnull().sum()

np.int64(490)

In [484]:
#Fill missing values using the median of the same neighborhood
df.groupby("Neighborhood")["Lot Frontage"].apply(
    lambda x: x.isnull().sum()
)

Neighborhood
Blmngtn     8
Blueste     0
BrDale      0
BrkSide    13
ClearCr    24
CollgCr    47
Crawfor    20
Edwards    16
Gilbert    54
Greens      1
GrnHill     2
IDOTRR      6
Landmrk     1
MeadowV     4
Mitchel    24
NAmes      68
NPkVill     2
NWAmes     46
NoRidge    17
NridgHt     3
OldTown    10
SWISU       4
Sawyer     53
SawyerW    19
Somerst    20
StoneBr     5
Timber     15
Veenker     8
Name: Lot Frontage, dtype: int64

In [485]:
#Because Lot Frontage depends heavily on the neighborhood. Using the neighborhood median preserves local characteristics and produces more realistic values than using one median for the entire dataset.

In [486]:
df.groupby("Neighborhood")["Lot Frontage"].apply(
    lambda x: x.isnull().all()
)

Neighborhood
Blmngtn    False
Blueste    False
BrDale     False
BrkSide    False
ClearCr    False
CollgCr    False
Crawfor    False
Edwards    False
Gilbert    False
Greens     False
GrnHill     True
IDOTRR     False
Landmrk     True
MeadowV    False
Mitchel    False
NAmes      False
NPkVill    False
NWAmes     False
NoRidge    False
NridgHt    False
OldTown    False
SWISU      False
Sawyer     False
SawyerW    False
Somerst    False
StoneBr    False
Timber     False
Veenker    False
Name: Lot Frontage, dtype: bool

In [487]:
neighborhood_median = (
    df.groupby("Neighborhood")["Lot Frontage"]
      .median()
)

df["Lot Frontage"] = df["Lot Frontage"].fillna(
    df["Neighborhood"].map(neighborhood_median)
)
#Most missing values were filled using the median within each neighborhood because lot frontage depends on location. However, a few neighborhoods had no recorded frontage values at all, so no neighborhood median could be computed. For those remaining cases, I used the overall median as a fallback.

In [488]:
print(df["Lot Frontage"].isnull().sum())

3

In [489]:
problem_neighborhoods = (
    df.groupby("Neighborhood")["Lot Frontage"]
      .apply(lambda x: x.notna().sum())
)
#This applies the filter to the list, dropping all the healthy neighborhoods and displaying only the completely empty ones.
problem_neighborhoods[problem_neighborhoods == 0]

#This code is a diagnostic tool designed to identify the exact neighborhoods that are causing your RuntimeWarning by finding which ones have zero valid data points for "Lot Frontage"

Neighborhood
GrnHill    0
Landmrk    0
Name: Lot Frontage, dtype: int64

### Handling `Lot Frontage`

- `Lot Frontage` was first imputed using the median value within each `Neighborhood`.
- During validation, three records (`GrnHill` and `Landmrk`) still had missing values because those neighborhoods contained no valid `Lot Frontage` observations.
- For these rare cases, the overall dataset median was used as a fallback.
- This hierarchical imputation preserves neighborhood-specific information whenever possible while ensuring no missing values remain.

In [490]:
#check the data that has zero null values
# Fill missing Lot Frontage values using the median of each Neighborhood
#if there is no value then look into the median values

#  Calculate neighborhood medians
neighborhood_median = (
    df.groupby("Neighborhood")["Lot Frontage"]
      .median()
)

# Fill using neighborhood median
df["Lot Frontage"] = df["Lot Frontage"].fillna(
    df["Neighborhood"].map(neighborhood_median)
)

#Fill any remaining values using the overall median
overall_median = df["Lot Frontage"].median()

df["Lot Frontage"] = df["Lot Frontage"].fillna(overall_median)

#  Verify
print(df["Lot Frontage"].isnull().sum())

0

In [491]:
print(df["Mas Vnr Type"].value_counts(dropna=False))
print("-" * 50)
print(df["Mas Vnr Area"].describe())
print("Missing:", df["Mas Vnr Area"].isnull().sum())
#knowing the data

Mas Vnr Type
NaN        1775
BrkFace     880
Stone       249
BrkCmn       25
CBlock        1
Name: count, dtype: int64
--------------------------------------------------
count    2907.000000
mean      101.896801
std       179.112611
min         0.000000
25%         0.000000
50%         0.000000
75%       164.000000
max      1600.000000
Name: Mas Vnr Area, dtype: float64
Missing: 23

In [492]:
df["Mas Vnr Type"]=df["Mas Vnr Type"].fillna("None")
df["Mas Vnr Area"]=df["Mas Vnr Area"].fillna(0)

#both the categorial and the numeric values are filled
#fill Mas Vnr Area with 0 instead of the median
#Because the missing values correspond to houses without masonry veneer. An area of 0 correctly represents the absence of veneer, whereas the median would incorrectly assign veneer area to houses that do not have it.

In [493]:
print(df["Mas Vnr Type"].isnull().sum())
print(df["Mas Vnr Area"].isnull().sum())

0
0

In [494]:
df["Electrical"].value_counts(dropna=False)
#Since only one house is missing this value, replacing it with the most common category has almost no impact on the dataset.

Electrical
SBrkr    2682
FuseA     188
FuseF      50
FuseP       8
NaN         1
Mix         1
Name: count, dtype: int64

In [495]:
electrical_mode = df["Electrical"].mode()[0]
df["Electrical"]=df["Electrical"].fillna(electrical_mode)

In [496]:
df["Electrical"].isnull().sum()

np.int64(0)

Every missing value in the dataset has been handled.

In [497]:
missing_summary=df.isnull().sum()
missing_summary=missing_summary[missing_summary > 0]
missing_summary

Series([], dtype: int64)

In [498]:
print("Total Missing Values:", df.isnull().sum().sum())

Total Missing Values: 0

In [499]:
df.to_csv("/Users/saranraj/PycharmProjects/house_price_prediction/data/cleaned_house_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

Missing value handling

Domain-based imputation

Hierarchical imputation for Lot Frontage

Final validation

Saved cleaned dataset